DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;

CREATE TABLE IF NOT EXISTS users (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(256) NOT NULL,
	email varchar(512) NOT NULL,
	CONSTRAINT unq_email UNIQUE (email)
);
CREATE TABLE  IF NOT EXISTS items (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	owner bigint REFERENCES users(id),
	name varchar(256) NOT NULL,
	description varchar(2048) NOT NULL,
	status boolean NOT NULL
);
CREATE TABLE IF NOT EXISTS bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id bigint REFERENCES items(id),
    booker_id bigint REFERENCES users(id),
    start_time timestamp,
    end_time timestamp,
    status varchar(128)
);
CREATE TABLE IF NOT EXISTS comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id bigint REFERENCES items(id),
    user_id bigint REFERENCES users(id),
    text varchar(2048) NOT NULL,
    created timestamp
);
